services:
  - type: web
    name: qv-training-library-api
    env: node
    rootDir: server
    buildCommand: npm install
    startCommand: npm start
    autoDeploy: true
    envVars:
      - key: NODE_VERSION
        value: 20
      - key: MONGODB_URI
        sync: false
